// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using interview_question_010.Modules;

#nullable disable

namespace interview_question_010.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20260525063320_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("interview_question_010.Modules.Candicate.Models.t_candidate", b =>
                {
                    b.Property<Guid?>("candidate_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("candidate_fullname")
                        .HasColumnType("text");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("test_name")
                        .HasColumnType("text");

                    b.Property<Guid?>("test_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("candidate_uid");

                    b.ToTable("candidate", (string)null);
                });

            modelBuilder.Entity("interview_question_010.Modules.Candicate.Models.t_candidate_choice", b =>
                {
                    b.Property<Guid?>("candidate_choice_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("candidate_question_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("choice_name")
                        .HasColumnType("text");

                    b.Property<Guid?>("choice_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("is_correct")
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_selected")
                        .HasColumnType("boolean");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("candidate_choice_uid");

                    b.HasIndex("candidate_question_uid");

                    b.ToTable("candidate_choice", (string)null);
                });

            modelBuilder.Entity("interview_question_010.Modules.Candicate.Models.t_candidate_question", b =>
                {
                    b.Property<Guid?>("candidate_question_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("candidate_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("is_correct")
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("question_name")
                        .HasColumnType("text");

                    b.Property<Guid?>("question_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("candidate_question_uid");

                    b.HasIndex("candidate_uid");

                    b.ToTable("candidate_question", (string)null);
                });

            modelBuilder.Entity("interview_question_010.Modules.Candicate.Models.v_candidate", b =>
                {
                    b.Property<Guid?>("candidate_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("candidate_fullname")
                        .HasColumnType("text");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("test_name")
                        .HasColumnType("text");

                    b.Property<Guid?>("test_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("candidate_uid");

                    b.ToTable((string)null);

                    b.ToView("v_candidate", (string)null);
                });

            modelBuilder.Entity("interview_question_010.Modules.Candicate.Models.v_candidate_choice", b =>
                {
                    b.Property<Guid?>("candidate_choice_uid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("candidate_question_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("choice_name")
                        .HasColumnType("text");

                    b.Property<Guid?>("choice_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("is_correct")
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_selected")
                        .HasColumnType("boolean");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("candidate_choice_uid");

                    b.HasIndex("candidate_question_uid");

                    b.ToTable((string)null);

                    b.ToView("v_candidate_choice", (string)null);
                });

            modelBuilder.Entity("interview_question_010.Modules.Candicate.Models.v_candidate_question", b =>
                {
                    b.Property<Guid?>("candidate_question_uid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("candidate_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("is_correct")
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("question_name")
                        .HasColumnType("text");

                    b.Property<Guid?>("question_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("candidate_question_uid");

                    b.HasIndex("candidate_uid");

                    b.ToTable((string)null);

                    b.ToView("v_candidate_question", (string)null);
                });

            modelBuilder.Entity("interview_question_010.Modules.Test.Models.t_choice", b =>
                {
                    b.Property<Guid?>("choice_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("choice_name")
                        .HasColumnType("text");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("is_corrent")
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("question_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("choice_uid");

                    b.HasIndex("question_uid");

                    b.ToTable("choice", (string)null);
                });

            modelBuilder.Entity("interview_question_010.Modules.Test.Models.t_question", b =>
                {
                    b.Property<Guid?>("question_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("question_name")
                        .HasColumnType("text");

                    b.Property<Guid?>("test_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("question_uid");

                    b.HasIndex("test_uid");

                    b.ToTable("question", (string)null);
                });

            modelBuilder.Entity("interview_question_010.Modules.Test.Models.t_test", b =>
                {
                    b.Property<Guid?>("test_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("test_name")
                        .HasColumnType("text");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("test_uid");

                    b.ToTable("test", (string)null);
                });

            modelBuilder.Entity("interview_question_010.Modules.Test.Models.v_choice", b =>
                {
                    b.Property<Guid?>("choice_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("choice_name")
                        .HasColumnType("text");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("is_corrent")
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("question_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("choice_uid");

                    b.HasIndex("question_uid");

                    b.ToTable((string)null);

                    b.ToView("v_choice", (string)null);
                });

            modelBuilder.Entity("interview_question_010.Modules.Test.Models.v_question", b =>
                {
                    b.Property<Guid?>("question_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("question_name")
                        .HasColumnType("text");

                    b.Property<Guid?>("test_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("question_uid");

                    b.HasIndex("test_uid");

                    b.ToTable((string)null);

                    b.ToView("v_question", (string)null);
                });

            modelBuilder.Entity("interview_question_010.Modules.Test.Models.v_test", b =>
                {
                    b.Property<Guid?>("test_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("test_name")
                        .HasColumnType("text");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("test_uid");

                    b.ToTable((string)null);

                    b.ToView("v_test", (string)null);
                });

            modelBuilder.Entity("interview_question_010.Modules.Candicate.Models.t_candidate_choice", b =>
                {
                    b.HasOne("interview_question_010.Modules.Candicate.Models.t_candidate_question", "candidate_question")
                        .WithMany("candidate_choices")
                        .HasForeignKey("candidate_question_uid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("candidate_question");
                });

            modelBuilder.Entity("interview_question_010.Modules.Candicate.Models.t_candidate_question", b =>
                {
                    b.HasOne("interview_question_010.Modules.Candicate.Models.t_candidate", "candidate")
                        .WithMany("candidate_questions")
                        .HasForeignKey("candidate_uid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("candidate");
                });

            modelBuilder.Entity("interview_question_010.Modules.Candicate.Models.v_candidate_choice", b =>
                {
                    b.HasOne("interview_question_010.Modules.Candicate.Models.v_candidate_question", "candidate_question")
                        .WithMany("candidate_choices")
                        .HasForeignKey("candidate_question_uid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("candidate_question");
                });

            modelBuilder.Entity("interview_question_010.Modules.Candicate.Models.v_candidate_question", b =>
                {
                    b.HasOne("interview_question_010.Modules.Candicate.Models.v_candidate", "candidate")
                        .WithMany("candidate_questions")
                        .HasForeignKey("candidate_uid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("candidate");
                });

            modelBuilder.Entity("interview_question_010.Modules.Test.Models.t_choice", b =>
                {
                    b.HasOne("interview_question_010.Modules.Test.Models.t_question", "question")
                        .WithMany("choices")
                        .HasForeignKey("question_uid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("question");
                });

            modelBuilder.Entity("interview_question_010.Modules.Test.Models.t_question", b =>
                {
                    b.HasOne("interview_question_010.Modules.Test.Models.t_test", "test")
                        .WithMany("questions")
                        .HasForeignKey("test_uid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("test");
                });

            modelBuilder.Entity("interview_question_010.Modules.Test.Models.v_choice", b =>
                {
                    b.HasOne("interview_question_010.Modules.Test.Models.v_question", "question")
                        .WithMany("choices")
                        .HasForeignKey("question_uid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("question");
                });

            modelBuilder.Entity("interview_question_010.Modules.Test.Models.v_question", b =>
                {
                    b.HasOne("interview_question_010.Modules.Test.Models.v_test", "test")
                        .WithMany("questions")
                        .HasForeignKey("test_uid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("test");
                });

            modelBuilder.Entity("interview_question_010.Modules.Candicate.Models.t_candidate", b =>
                {
                    b.Navigation("candidate_questions");
                });

            modelBuilder.Entity("interview_question_010.Modules.Candicate.Models.t_candidate_question", b =>
                {
                    b.Navigation("candidate_choices");
                });

            modelBuilder.Entity("interview_question_010.Modules.Candicate.Models.v_candidate", b =>
                {
                    b.Navigation("candidate_questions");
                });

            modelBuilder.Entity("interview_question_010.Modules.Candicate.Models.v_candidate_question", b =>
                {
                    b.Navigation("candidate_choices");
                });

            modelBuilder.Entity("interview_question_010.Modules.Test.Models.t_question", b =>
                {
                    b.Navigation("choices");
                });

            modelBuilder.Entity("interview_question_010.Modules.Test.Models.t_test", b =>
                {
                    b.Navigation("questions");
                });

            modelBuilder.Entity("interview_question_010.Modules.Test.Models.v_question", b =>
                {
                    b.Navigation("choices");
                });

            modelBuilder.Entity("interview_question_010.Modules.Test.Models.v_test", b =>
                {
                    b.Navigation("questions");
                });
#pragma warning restore 612, 618
        }
    }
}
